spring:
  application:
    name: producer-1
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        output-channel:
          destination: test_topic_1
          contentType: application/json
server:
  port: 8081