spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input-channel:
          group: group2
          destination: test_topic
          contentType: application/json