spring:
  application:
    name: consumer-2
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input-channel:
          group: group2
          destination: test_topic_1
          contentType: application/json